import Foundation

// Bundled copy of the vehicle reference data (vehicle_reference.json, generated by
// scripts/gen-seed.js from the researched CSVs). Bundled rather than fetched because
// Setup must work in a field with no signal; the Supabase copy of the same tables exists
// for future in-place data updates, not as a first-run dependency.

struct SetupPreset: Decodable, Identifiable {
    let id: String
    let name: String
    let silhouette: String   // lowtop | hightop | compact
    let genId: String
}

struct GenerationRef: Decodable, Identifiable {
    let genId: String
    let make: String
    let model: String
    let generation: String
    let yearFrom: Int?
    let yearTo: Int?
    let badges: String?
    let wheelbasesMm: [Int]
    let trackFrontMm: Int?
    let trackRearMm: Int?
    let trackConfidence: String
    var id: String { genId }
}

struct ChassisTypeRef: Decodable, Identifiable {
    let chassisId: String
    let chassisType: String
    let axleConfig: String
    var id: String { chassisId }
}

struct RampProfileRef: Decodable, Identifiable {
    let id: String
    let name: String
    let stepsMm: [Int]
    let pro: Bool
}

struct ReferenceData: Decodable {
    let alkoTypicalRearTrackMM: Int
    let setupPresets: [SetupPreset]
    let generations: [GenerationRef]
    let chassisTypes: [ChassisTypeRef]
    let rampProfiles: [RampProfileRef]
}

final class ReferenceStore {
    static let shared = ReferenceStore()
    let data: ReferenceData

    private init() {
        guard let url = Bundle.main.url(forResource: "vehicle_reference", withExtension: "json"),
              let raw = try? Data(contentsOf: url) else {
            fatalError("vehicle_reference.json missing from bundle — run scripts/gen-seed.js")
        }
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        do {
            data = try decoder.decode(ReferenceData.self, from: raw)
        } catch {
            fatalError("vehicle_reference.json failed to decode: \(error)")
        }
    }

    func generation(id: String) -> GenerationRef? {
        data.generations.first { $0.genId == id }
    }

    func rampProfile(id: String) -> RampProfileRef? {
        data.rampProfiles.first { $0.id == id }
    }

    /// MOT-lookup result -> preset match. Make + year resolve the generation (the
    /// badge+year trap: a 2016 Vivaro is a Trafic twin, a 2020 one a Stellantis van).
    func matchPreset(make: String, model: String?, year: Int?) -> SetupPreset? {
        let m = make.uppercased()
        let mod = (model ?? "").uppercased()
        for preset in data.setupPresets {
            guard let gen = generation(id: preset.genId) else { continue }
            let makeMatches = gen.make.uppercased().contains(m) || m.contains(gen.make.uppercased())
                || (gen.badges ?? "").uppercased().contains(m)
            guard makeMatches else { continue }
            if !mod.isEmpty {
                let modelWords = gen.model.uppercased().split(separator: " ")
                if modelWords.contains(where: { mod.contains($0) }) { return preset }
            }
            if let y = year, let from = gen.yearFrom {
                if y >= from && (gen.yearTo == nil || y <= gen.yearTo!) { return preset }
            }
        }
        return nil
    }
}
