import Foundation
import LevelSpotCore

// Bundled copy of the vehicle reference data (vehicle_reference.json, generated by
// scripts/gen-seed.js from the researched CSVs). Bundled rather than fetched because
// Setup must work in a field with no signal; the Supabase copy of the same tables exists
// for future in-place data updates, not as a first-run dependency.

struct SetupPreset: Decodable, Identifiable {
    let id: String
    let name: String
    let silhouette: String   // lowtop | hightop | compact
    let genId: String
}

struct GenerationRef: Decodable, Identifiable {
    let genId: String
    let make: String
    let model: String
    let generation: String
    let yearFrom: Int?
    let yearTo: Int?
    let badges: String?
    let wheelbasesMm: [Int]
    let trackFrontMm: Int?
    let trackRearMm: Int?
    let trackConfidence: String
    var id: String { genId }
}

struct ChassisTypeRef: Decodable, Identifiable {
    let chassisId: String
    let chassisType: String
    let axleConfig: String
    var id: String { chassisId }
}

struct RampProfileRef: Decodable, Identifiable {
    let id: String
    let name: String
    let stepsMm: [Int]
    let pro: Bool
    let kind: String?         // RampKind raw; absent ⇒ "stepped" (back-compat with old data)
    let maxLiftMm: Int?       // continuous ceiling
    let incrementMm: Int?     // ≈ block height for stackable blocks

    var rampKind: RampKind { RampKind(rawValue: kind ?? "stepped") ?? .stepped }
    var ceilingMM: Int { rampKind == .stepped ? (stepsMm.max() ?? 0) : (maxLiftMm ?? 0) }

    /// The capability handed to the levelling maths.
    var rampSet: RampSet {
        RampSet(kind: rampKind, stepsMM: stepsMm,
                maxLiftMM: maxLiftMm ?? (stepsMm.max() ?? 0), incrementMM: incrementMm ?? 0)
    }

    /// One-line capacity summary for the Setup rows.
    var capacityLabel: String {
        switch rampKind {
        case .stepped: return stepsMm.map(String.init).joined(separator: " / ") + "mm"
        case .blocks: return "up to \(ceilingMM)mm · stackable blocks"
        case .inflatable: return "up to \(ceilingMM)mm · inflatable"
        case .ratchet: return "up to \(ceilingMM)mm · ratchet"
        case .wedge: return "up to \(ceilingMM)mm · drive-on wedge"
        }
    }
}

struct ReferenceData: Decodable {
    let alkoTypicalRearTrackMM: Int
    let setupPresets: [SetupPreset]
    let generations: [GenerationRef]
    let chassisTypes: [ChassisTypeRef]
    let rampProfiles: [RampProfileRef]
}

final class ReferenceStore {
    static let shared = ReferenceStore()
    let data: ReferenceData

    private init() {
        guard let url = Bundle.main.url(forResource: "vehicle_reference", withExtension: "json"),
              let raw = try? Data(contentsOf: url) else {
            fatalError("vehicle_reference.json missing from bundle — run scripts/gen-seed.js")
        }
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        do {
            data = try decoder.decode(ReferenceData.self, from: raw)
        } catch {
            fatalError("vehicle_reference.json failed to decode: \(error)")
        }
    }

    func generation(id: String) -> GenerationRef? {
        data.generations.first { $0.genId == id }
    }

    func rampProfile(id: String) -> RampProfileRef? {
        data.rampProfiles.first { $0.id == id }
    }

    /// MOT-lookup result -> preset match. Make + year resolve the generation (the
    /// badge+year trap: a 2016 Vivaro is a Trafic twin, a 2020 one a Stellantis van).
    func matchPreset(make: String, model: String?, year: Int?) -> SetupPreset? {
        let m = make.uppercased()
        let mod = (model ?? "").uppercased()
        var makeMatches: [SetupPreset] = []
        for preset in data.setupPresets {
            guard let gen = generation(id: preset.genId) else { continue }
            let makeOK = gen.make.uppercased().contains(m) || m.contains(gen.make.uppercased())
                || (gen.badges ?? "").uppercased().contains(m)
            guard makeOK else { continue }
            makeMatches.append(preset)
            // Strongest signal: the model name appears in the DVSA model string.
            if !mod.isEmpty {
                let modelWords = gen.model.uppercased().split(separator: " ")
                if modelWords.contains(where: { mod.contains($0) }) { return preset }
            }
            // Next: the registration year sits inside this generation's production run.
            if let y = year, let from = gen.yearFrom {
                if y >= from && (gen.yearTo == nil || y <= gen.yearTo!) { return preset }
            }
        }
        // Fallback: the make matched exactly one vehicle in our list (e.g. Fiat -> Ducato),
        // so it's unambiguous even when the DVSA model/year didn't line up. Pre-selecting the
        // obvious vehicle beats leaving the lookup feeling like a dead end.
        return makeMatches.count == 1 ? makeMatches.first : nil
    }
}
